# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POu5AZhDfo_xSVrRVFn8Ni2hx9IEXDP_
"""

from joblib import dump,load
import pandas as pd
# Read data from local files
data = pd.read_csv('datasets_diabetes.csv')

print(data.head())
print(type(data))

X = data.iloc[:,[1,2,4,5,7]].values
y = data.iloc[:,8].values

print(X.shape)
print(y.shape)
print(type(X))
print(type(y))

# Split the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Shape of training and testing datasets
print(X_train.shape)
print(X_test.shape)

# Using Random Forest for classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20, criterion='entropy')
classifier.fit(X_train, y_train)

# Saving model
dump(classifier, open('model.pkl', 'wb'))

# Testing the accuracy from the model
model = load(open('model.pkl', 'rb'))

from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
score = accuracy_score(y_test, y_pred)

print(f'Accuracy on test score : {score}')